types : ['infj', 'infp', 'intj', 'intp', 'istj', 'istp', 'isfp','isfj', 'enfj', 'enfp','infj', 'infp', 'intj', 'intp', 'istj', 'istp', 'isfp','isfj', 'enfj', 'enfp', 'entj', 'entp', 'estj', 'estp', 'esfp', 'esfj']
my_stop_words : ['ni', 'ti', 'ne', 'te', 'se']
valid_models: ['LogisticRegression', 'RandomForest']
model_parameters:
   tfidf:
      sublinear_tf: True
      min_df: 10
      ngram_range: [1,2]
   LogisticRegression:
      random_state: 0
      solver: 'lbfgs'
      class_weight: Null
      max_iter: 500
   RandomForest:
      n_estimators: 200
      max_depth: 3
      random_state: 0
   svc:
      C: 1
      gamma: 1
      kernel: 'rbf'
file_paths:
   data:
      'data/mbti.csv'
   models:
      LogisticRegression:
         'LogisticRegression.pkl'
      RandomForest:
         'RandomForest.pkl'
      tfidf:
         'tfidf_vec.pkl'
   accuracy:
      LogisticRegression:
         'LogisticRegression_accuracy.pkl'
      RandomForest:
         'RandomForest_accuracy.pkl'

