types : ['infj', 'infp', 'intj', 'intp', 'istj', 'istp', 'isfp','isfj', 'enfj', 'enfp','infj', 'infp', 'intj', 'intp', 'istj', 'istp', 'isfp','isfj', 'enfj', 'enfp', 'entj', 'entp', 'estj', 'estp', 'esfp', 'esfj']
my_stop_words : ['ni', 'ti', 'ne', 'te', 'se']
tfidf_params:
   sublinear_tf: True
   min_df: 10
   ngram_range: [1,2]
lr_params:
   random_state: 0
   solver: 'lbfgs'
   class_weight: Null
   max_iter: 100
rf_params:
   n_estimators: 200
   max_depth: 3
   random_state: 0
svc_params:
   C: 1
   gamma: 1
   kernel: 'rbf'
