FROM python:3.8-slim

WORKDIR /dash_app
COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY ./dash_app ./dash_app
COPY ./personality_classifier ./personality_classifier
COPY config.yml config.yml
COPY setup.py setup.py

RUN pip3 install -e .

EXPOSE 8050

CMD ["python", "dash_app/app.py", "--host", "0.0.0.0"]
