FROM python:3.8-slim

WORKDIR /dash_app
COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY ./dash_app ./dash_app
COPY config.yml config.yml

EXPOSE 8050

CMD ["python", "dash_app/app.py", "--host", "0.0.0.0"]
